version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: web
    container_name: web
    hostname: web
    restart: always
    command: python3 /code/manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/web
    ports:
      - "8080:8080"
    depends_on:
      - mysql  

  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    ports:
      - 3306:3306
    environment:
      - MYSQL_HOST=localhost 
      - MYSQL_PORT=3306 
      - MYSQL_DATABASE=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_HOST= '%'  # needs to be enclosed with quotes
