# Generated by Django 3.1.7 on 2021-03-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('BuildingID', models.IntegerField(primary_key=True, serialize=False)),
                ('Building_Name', models.CharField(max_length=64)),
                ('Building_Addr', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('PID', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('Office_Addr', models.CharField(default='', max_length=100)),
                ('FirstName', models.CharField(default='First name', max_length=100)),
                ('LastName', models.CharField(default='Last name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('NetworkID', models.IntegerField(primary_key=True, serialize=False)),
                ('DeviceID', models.CharField(default='', max_length=100)),
                ('Hostname', models.CharField(max_length=64)),
                ('Aliases', models.CharField(max_length=64)),
                ('IPv4', models.GenericIPAddressField()),
                ('IPv6', models.GenericIPAddressField()),
                ('BuildingID', models.IntegerField()),
                ('create_Date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserPID', models.CharField(default='', max_length=100)),
                ('DeviceID', models.CharField(default='', max_length=100)),
                ('Note', models.CharField(default='', max_length=100)),
                ('isHomeUse', models.BooleanField(default=False)),
                ('CheckoutDate', models.DateField(auto_now=True)),
                ('ReturnDate', models.DateField(default='YYYY-MM-DD')),
            ],
            options={
                'unique_together': {('UserPID', 'DeviceID', 'CheckoutDate')},
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serial_Number', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.CharField(default='', max_length=100)),
                ('VT_Tag', models.CharField(default='', max_length=100)),
                ('CS_Tag', models.CharField(default='', max_length=100)),
                ('acq_date', models.DateField(default='YYYY-MM-DD')),
                ('status', models.CharField(choices=[('In Use', 'In Use'), ('In Storage', 'In Storage'), ('On Loan', 'On Loan'), ('Damaged', 'Damaged'), ('Missing', 'Missing'), ('Surplused', 'Surplused'), ('Transferred', 'Transferred'), ('Written Off', 'Written Off'), ('Orphaned', 'Orphaned')], default='In Use', max_length=15)),
                ('issue', models.CharField(default='No issues', max_length=100)),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('VT_Tag', 'CS_Tag')},
            },
        ),
    ]
