# Generated by Django 3.1.7 on 2021-03-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('BuildingID', models.IntegerField(primary_key=True, serialize=False)),
                ('Building_Name', models.CharField(max_length=64)),
                ('Building_Addr', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.CharField(default='', editable=False, max_length=100)),
                ('Office_Addr', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('NetworkID', models.IntegerField(primary_key=True, serialize=False)),
                ('DeviceID', models.CharField(default='', max_length=100)),
                ('Hostname', models.CharField(max_length=64)),
                ('Aliases', models.CharField(max_length=64)),
                ('IPv4', models.GenericIPAddressField()),
                ('IPv6', models.GenericIPAddressField()),
                ('BuildingID', models.IntegerField()),
                ('create_Date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserPID', models.CharField(default='', max_length=100)),
                ('DeviceID', models.CharField(default='', max_length=100)),
                ('Note', models.CharField(default='', max_length=100)),
                ('isHomeUse', models.BooleanField(default=False)),
                ('CheckoutDate', models.DateField(auto_now=True)),
                ('ReturnDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField()),
                ('Manufacturer', models.CharField(default='', max_length=100)),
                ('Model', models.CharField(default='', max_length=100)),
                ('VT_Tag', models.CharField(default='', max_length=100)),
                ('CS_Tag', models.CharField(default='', max_length=100)),
                ('Serial_Number', models.CharField(default='', max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item Sold'), ('RESTOCKING', 'Item restocking in few days')], default='SOLD', max_length=10)),
                ('issue', models.CharField(default='No issues', max_length=100)),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('VT_Tag', 'CS_Tag')},
            },
        ),
    ]
