# Generated by Django 3.1.7 on 2021-03-30 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['CS_Tag']},
        ),
        migrations.AddField(
            model_name='building',
            name='IPv6_prefix',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='Address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='isCheckedOut',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='building',
            name='BuildingID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='CS_Tag',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='networkinterface',
            name='NetworkID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='HistoricalUserDevice',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('UserPID', models.CharField(default='', max_length=100)),
                ('DeviceID', models.CharField(default='', max_length=100)),
                ('Note', models.CharField(default='', max_length=100)),
                ('isHomeUse', models.BooleanField(default=False)),
                ('isCheckedOut', models.BooleanField(default=False)),
                ('Address', models.CharField(default='', max_length=100)),
                ('CheckoutDate', models.DateField(blank=True, editable=False)),
                ('ReturnDate', models.DateField(default='YYYY-MM-DD')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user device',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNetworkInterface',
            fields=[
                ('NetworkID', models.IntegerField(blank=True, db_index=True)),
                ('DeviceID', models.CharField(default='', max_length=100)),
                ('Hostname', models.CharField(max_length=64)),
                ('Aliases', models.CharField(max_length=64)),
                ('IPv4', models.GenericIPAddressField()),
                ('IPv6', models.GenericIPAddressField()),
                ('BuildingID', models.IntegerField()),
                ('create_Date', models.DateField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical network interface',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFaculty',
            fields=[
                ('PID', models.CharField(db_index=True, default='', max_length=100)),
                ('Office_Addr', models.CharField(default='', max_length=100)),
                ('FirstName', models.CharField(default='First name', max_length=100)),
                ('LastName', models.CharField(default='Last name', max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical faculty',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDevice',
            fields=[
                ('Serial_Number', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.CharField(default='', max_length=100)),
                ('VT_Tag', models.CharField(default='', max_length=100)),
                ('CS_Tag', models.CharField(db_index=True, default='', max_length=100)),
                ('acq_date', models.DateField(default='YYYY-MM-DD')),
                ('status', models.CharField(choices=[('In Use', 'In Use'), ('In Storage', 'In Storage'), ('On Loan', 'On Loan'), ('Damaged', 'Damaged'), ('Missing', 'Missing'), ('Surplused', 'Surplused'), ('Transferred', 'Transferred'), ('Written Off', 'Written Off'), ('Orphaned', 'Orphaned')], default='In Use', max_length=15)),
                ('issue', models.CharField(default='No issues', max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical device',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBuilding',
            fields=[
                ('BuildingID', models.IntegerField(blank=True, db_index=True)),
                ('Building_Name', models.CharField(max_length=64)),
                ('Building_Addr', models.CharField(max_length=64)),
                ('IPv6_prefix', models.GenericIPAddressField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical building',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='device',
            name='id',
        ),
    ]
