# Generated by Django 3.0.8 on 2021-02-10 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_desktop_laptop_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aliases', models.CharField(max_length=64)),
                ('IP_Address', models.CharField(max_length=64)),
                ('IPv6_Address', models.EmailField(max_length=254)),
                ('MAC_Address', models.CharField(max_length=64)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('Hostname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Event')),
            ],
        ),
    ]
