# Generated by Django 3.0.8 on 2021-02-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktop',
            name='CS_Tag',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='desktop',
            name='Manufacturer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='desktop',
            name='Model',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='desktop',
            name='Serial_Number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='desktop',
            name='VT_Tag',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='laptop',
            name='CS_Tag',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='laptop',
            name='Manufacturer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='laptop',
            name='Model',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='laptop',
            name='Serial_Number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='laptop',
            name='VT_Tag',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mobile',
            name='CS_Tag',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mobile',
            name='Manufacturer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mobile',
            name='Model',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mobile',
            name='Serial_Number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mobile',
            name='VT_Tag',
            field=models.CharField(default='', max_length=100),
        ),
    ]
