# Generated by Django 3.0.8 on 2021-02-10 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20210210_1715'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Ticket',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='event',
            new_name='ticket',
        ),
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together={('phone', 'ticket')},
        ),
    ]
