# Generated by Django 3.0.8 on 2021-02-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20210210_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostname',
            name='Hostname',
            field=models.CharField(max_length=64),
        ),
    ]
