# Generated by Django 3.0.8 on 2021-02-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20210210_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostname',
            name='IPv6_Address',
            field=models.CharField(max_length=64),
        ),
    ]
